# Generated by Django 4.0.3 on 2022-12-08 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obj_name', models.CharField(default='', max_length=20, verbose_name='结点1名称')),
                ('obj_type', models.CharField(default='', max_length=20, verbose_name='结点1类型')),
                ('rel_name', models.CharField(default='', max_length=20, verbose_name='关系名称')),
                ('rel_type', models.CharField(default='', max_length=20, verbose_name='关系类型')),
                ('sub_name', models.CharField(default='', max_length=20, verbose_name='结点2类型')),
                ('sub_type', models.CharField(default='', max_length=20, verbose_name='结点2类型')),
            ],
            options={
                'verbose_name': '关系表',
                'verbose_name_plural': '关系表',
                'db_table': 'Rel',
            },
        ),
    ]
