# Generated by Django 4.1.7 on 2023-08-23 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_rel_sub_uuid_alter_rel_obj_uuid"),
    ]

    operations = [
        migrations.DeleteModel(name="Rel",),
    ]
